version: '3.8'

services:
  landing-page:
    build: ./frontend/landing-page-service
    ports:
      - "3001:3000"
    container_name: landing-page-service

  analytics:
    build: ./backend/analytics-service
    ports:
      - "4000:4000"
    container_name: analytics-service
